version: '3'

services:
    magnitkarunclient:
        build: ./

        container_name: 'magnitkarunclient'
        image: ulidev/magnitkarunclient:v1.0.0

        user: '1000:1000'

        restart: always

        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        read_only: true
        tmpfs:
            - /tmp

        ports:
            - '127.0.0.1:3000:3000'

        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:3000',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
